// Generated by tools/sw-build.mjs: do not edit by hand. After changing any shipped file, run
//   node tools/sw-build.mjs captain-fold
// Precaches the game's own files and serves cache-first; CACHE_VERSION is a hash of those files.
var CACHE_VERSION = 'captain-fold-d0404b8c';
var FILES = [
  './',
  'audio.js',
  'core.js',
  'courses.js',
  'demo.js',
  'favicon-32.png',
  'flight.js',
  'fonts/Saira-OFL.txt',
  'fonts/Saira-var.woff2',
  'fonts/SairaStencilOne-OFL.txt',
  'fonts/SairaStencilOne.woff2',
  'game.js',
  'icon-192.png',
  'icon-512.png',
  'icon-maskable-512.png',
  'index.html',
  'input.js',
  'manifest.json',
  'progress.js',
  'register-sw.js',
  'render.js',
  'save.js',
  'skin.css',
  'sprites.js',
  'theme.js',
  'tokens.css',
  'ui-kit.css',
  'ui-kit.js'
];

self.addEventListener('install', function (e) {
  e.waitUntil(caches.open(CACHE_VERSION).then(function (c) { return c.addAll(FILES); }).then(function () { return self.skipWaiting(); }));
});

self.addEventListener('activate', function (e) {
  e.waitUntil(caches.keys().then(function (keys) {
    return Promise.all(keys.filter(function (k) { return k.indexOf('captain-fold-') === 0 && k !== CACHE_VERSION; })
      .map(function (k) { return caches.delete(k); }));
  }).then(function () { return self.clients.claim(); }));
});

self.addEventListener('fetch', function (e) {
  if (e.request.method !== 'GET') return;
  e.respondWith(caches.match(e.request, { ignoreSearch: true }).then(function (hit) { return hit || fetch(e.request); }));
});
