// GENERATED by tools/potion-pour/gen-levels.mjs -- do not hand-edit. Re-run the script to regenerate.
// Ladder per the design brief §9: capacity 4, 2 empty vials always, colours/par climbing by band, every 5th
// level a breather. Every level is solver-verified solvable at generation time and minMoves is the solver's
// proven optimum ("par" in the brief).
// Chapter medians (min-move, strictly rising): 6, 9, 13, 17, 19, 24
// L5-10 "which pour first?" check (>=3 legal first pours, at least one losing): 0/6 pass.
// Slowest solver re-verify across this ladder: 995ms.
(function (root) {
  const LEVELS = [
  {
    "level": 1,
    "chapter": 0,
    "colors": 2,
    "capacity": 4,
    "vials": [
      [
        0,
        0
      ],
      [],
      [
        1,
        1
      ],
      [
        1,
        1,
        0,
        0
      ]
    ],
    "minMoves": 2,
    "unlimitedUndo": true,
    "breather": false
  },
  {
    "level": 2,
    "chapter": 0,
    "colors": 3,
    "capacity": 4,
    "vials": [
      [
        0,
        0,
        1,
        1
      ],
      [
        1,
        2,
        1,
        2
      ],
      [],
      [
        2,
        2
      ],
      [
        0,
        0
      ]
    ],
    "minMoves": 6,
    "unlimitedUndo": true,
    "breather": false
  },
  {
    "level": 3,
    "chapter": 0,
    "colors": 3,
    "capacity": 4,
    "vials": [
      [
        2,
        2
      ],
      [
        1,
        1,
        1
      ],
      [
        0,
        0,
        0
      ],
      [
        0
      ],
      [
        2,
        2,
        1
      ]
    ],
    "minMoves": 3,
    "unlimitedUndo": true,
    "breather": false
  },
  {
    "level": 4,
    "chapter": 0,
    "colors": 3,
    "capacity": 4,
    "vials": [
      [],
      [
        0,
        0,
        1
      ],
      [
        2,
        2
      ],
      [
        1,
        1,
        0,
        0
      ],
      [
        2,
        2,
        1
      ]
    ],
    "minMoves": 4,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 5,
    "chapter": 0,
    "colors": 2,
    "capacity": 4,
    "vials": [
      [
        0,
        0,
        1
      ],
      [
        1,
        1
      ],
      [
        0,
        0,
        1
      ],
      []
    ],
    "minMoves": 3,
    "unlimitedUndo": false,
    "breather": true
  },
  {
    "level": 6,
    "chapter": 0,
    "colors": 3,
    "capacity": 4,
    "vials": [
      [
        0,
        0,
        2,
        2
      ],
      [
        1,
        1,
        0
      ],
      [
        1,
        0
      ],
      [
        2,
        2,
        1
      ],
      []
    ],
    "minMoves": 5,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 7,
    "chapter": 0,
    "colors": 4,
    "capacity": 4,
    "vials": [
      [
        0,
        0,
        0,
        1
      ],
      [],
      [
        2,
        2,
        2,
        0
      ],
      [
        3,
        3,
        3
      ],
      [
        1,
        1,
        3,
        1
      ],
      [
        2
      ]
    ],
    "minMoves": 6,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 8,
    "chapter": 0,
    "colors": 4,
    "capacity": 4,
    "vials": [
      [
        0,
        3,
        3,
        2
      ],
      [
        1,
        1
      ],
      [
        0,
        2
      ],
      [
        3,
        3
      ],
      [
        2,
        2
      ],
      [
        1,
        1,
        0,
        0
      ]
    ],
    "minMoves": 6,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 9,
    "chapter": 0,
    "colors": 4,
    "capacity": 4,
    "vials": [
      [
        1,
        0,
        1
      ],
      [
        1,
        3
      ],
      [
        2,
        2,
        2,
        2
      ],
      [
        0
      ],
      [
        1,
        3,
        3,
        3
      ],
      [
        0,
        0
      ]
    ],
    "minMoves": 7,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 10,
    "chapter": 0,
    "colors": 3,
    "capacity": 4,
    "vials": [
      [
        0,
        1,
        0
      ],
      [
        1,
        1
      ],
      [
        2,
        2,
        2,
        0
      ],
      [
        0,
        1
      ],
      [
        2
      ]
    ],
    "minMoves": 6,
    "unlimitedUndo": false,
    "breather": true
  },
  {
    "level": 11,
    "chapter": 1,
    "colors": 4,
    "capacity": 4,
    "vials": [
      [
        0,
        1
      ],
      [
        1,
        0
      ],
      [
        1,
        1
      ],
      [
        3,
        3,
        2
      ],
      [
        2,
        2,
        2
      ],
      [
        0,
        3,
        3,
        0
      ]
    ],
    "minMoves": 7,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 12,
    "chapter": 1,
    "colors": 4,
    "capacity": 4,
    "vials": [
      [
        0,
        2,
        2,
        3
      ],
      [],
      [
        1,
        1,
        0
      ],
      [
        3,
        3,
        3,
        1
      ],
      [
        2,
        2,
        0,
        1
      ],
      [
        0
      ]
    ],
    "minMoves": 7,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 13,
    "chapter": 1,
    "colors": 4,
    "capacity": 4,
    "vials": [
      [
        0,
        0,
        0,
        3
      ],
      [
        1,
        0,
        2,
        1
      ],
      [],
      [
        2,
        2
      ],
      [
        3,
        3,
        1,
        1
      ],
      [
        3,
        2
      ]
    ],
    "minMoves": 8,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 14,
    "chapter": 1,
    "colors": 4,
    "capacity": 4,
    "vials": [
      [
        2,
        3,
        0,
        1
      ],
      [],
      [
        2,
        3,
        1,
        1
      ],
      [
        3,
        3
      ],
      [
        0,
        0,
        0,
        1
      ],
      [
        2,
        2
      ]
    ],
    "minMoves": 8,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 15,
    "chapter": 1,
    "colors": 3,
    "capacity": 4,
    "vials": [
      [
        1
      ],
      [
        2,
        2,
        1,
        0
      ],
      [
        2,
        1,
        0,
        0
      ],
      [
        0,
        1
      ],
      [
        2
      ]
    ],
    "minMoves": 7,
    "unlimitedUndo": false,
    "breather": true
  },
  {
    "level": 16,
    "chapter": 1,
    "colors": 5,
    "capacity": 4,
    "vials": [
      [
        0
      ],
      [
        4,
        4,
        4,
        1
      ],
      [
        2,
        2,
        2,
        0
      ],
      [
        3,
        3,
        2,
        3
      ],
      [
        0,
        0,
        1,
        4
      ],
      [
        1
      ],
      [
        1,
        3
      ]
    ],
    "minMoves": 9,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 17,
    "chapter": 1,
    "colors": 5,
    "capacity": 4,
    "vials": [
      [
        0,
        2
      ],
      [
        3,
        1,
        1,
        0
      ],
      [
        2,
        0,
        0
      ],
      [
        3,
        2
      ],
      [
        4,
        4,
        4
      ],
      [
        3,
        3,
        1,
        1
      ],
      [
        4,
        2
      ]
    ],
    "minMoves": 10,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 18,
    "chapter": 1,
    "colors": 5,
    "capacity": 4,
    "vials": [
      [
        0,
        2
      ],
      [
        4,
        1,
        0,
        0
      ],
      [],
      [
        3,
        1,
        1
      ],
      [
        4,
        4,
        4,
        2
      ],
      [
        1,
        3,
        2,
        2
      ],
      [
        3,
        3,
        0
      ]
    ],
    "minMoves": 10,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 19,
    "chapter": 1,
    "colors": 5,
    "capacity": 4,
    "vials": [
      [
        3,
        3,
        1
      ],
      [
        1,
        3,
        0,
        4
      ],
      [
        2,
        2,
        2,
        0
      ],
      [
        3,
        1,
        0,
        1
      ],
      [
        4,
        4,
        4,
        0
      ],
      [],
      [
        2
      ]
    ],
    "minMoves": 11,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 20,
    "chapter": 1,
    "colors": 4,
    "capacity": 4,
    "vials": [
      [
        0,
        1,
        1,
        0
      ],
      [],
      [
        2,
        2,
        2,
        1
      ],
      [
        3,
        0,
        2,
        0
      ],
      [],
      [
        3,
        3,
        3,
        1
      ]
    ],
    "minMoves": 9,
    "unlimitedUndo": false,
    "breather": true
  },
  {
    "level": 21,
    "chapter": 2,
    "colors": 5,
    "capacity": 4,
    "vials": [
      [
        1,
        2,
        0,
        0
      ],
      [
        1,
        4,
        1
      ],
      [
        2,
        2,
        2
      ],
      [
        3,
        4,
        3
      ],
      [
        4,
        0,
        0
      ],
      [
        3,
        3,
        1,
        4
      ],
      []
    ],
    "minMoves": 11,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 22,
    "chapter": 2,
    "colors": 5,
    "capacity": 4,
    "vials": [
      [
        0,
        1,
        1,
        2
      ],
      [
        1,
        0,
        2
      ],
      [
        2,
        2,
        4
      ],
      [
        3,
        3,
        1,
        4
      ],
      [
        4,
        3
      ],
      [],
      [
        0,
        0,
        3,
        4
      ]
    ],
    "minMoves": 11,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 23,
    "chapter": 2,
    "colors": 5,
    "capacity": 4,
    "vials": [
      [
        3,
        3,
        1,
        1
      ],
      [
        2,
        0,
        3,
        4
      ],
      [
        4,
        0,
        0,
        2
      ],
      [
        4
      ],
      [
        4,
        1,
        1
      ],
      [
        2,
        2,
        0,
        3
      ],
      []
    ],
    "minMoves": 12,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 24,
    "chapter": 2,
    "colors": 5,
    "capacity": 4,
    "vials": [
      [
        0,
        0,
        2
      ],
      [
        0,
        4,
        1,
        1
      ],
      [
        2,
        3,
        4
      ],
      [
        3,
        3,
        2
      ],
      [
        3,
        1
      ],
      [
        4,
        4,
        1
      ],
      [
        0,
        2
      ]
    ],
    "minMoves": 12,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 25,
    "chapter": 2,
    "colors": 4,
    "capacity": 4,
    "vials": [
      [
        0,
        1,
        2,
        1
      ],
      [
        2
      ],
      [
        0,
        2,
        1,
        0
      ],
      [
        1,
        0,
        3
      ],
      [],
      [
        3,
        2,
        3,
        3
      ]
    ],
    "minMoves": 12,
    "unlimitedUndo": false,
    "breather": true
  },
  {
    "level": 26,
    "chapter": 2,
    "colors": 6,
    "capacity": 4,
    "vials": [
      [
        5,
        5
      ],
      [
        1,
        1,
        3
      ],
      [
        2,
        2,
        5
      ],
      [
        3,
        3,
        5,
        1
      ],
      [
        4,
        1,
        0,
        0
      ],
      [
        3
      ],
      [
        4,
        2,
        2,
        4
      ],
      [
        0,
        4,
        0
      ]
    ],
    "minMoves": 13,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 27,
    "chapter": 2,
    "colors": 6,
    "capacity": 4,
    "vials": [
      [
        0,
        5
      ],
      [
        1,
        1,
        0,
        0
      ],
      [
        2,
        1,
        4,
        2
      ],
      [
        3,
        3,
        3,
        0
      ],
      [
        4,
        5
      ],
      [
        4
      ],
      [
        2,
        3,
        2,
        4
      ],
      [
        5,
        1,
        5
      ]
    ],
    "minMoves": 14,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 28,
    "chapter": 2,
    "colors": 6,
    "capacity": 4,
    "vials": [
      [
        0,
        0,
        5
      ],
      [
        1,
        1,
        2
      ],
      [
        5,
        3,
        3
      ],
      [
        3,
        3,
        4
      ],
      [
        1,
        0
      ],
      [
        5,
        4,
        4,
        1
      ],
      [
        0,
        4
      ],
      [
        2,
        5,
        2,
        2
      ]
    ],
    "minMoves": 14,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 29,
    "chapter": 2,
    "colors": 6,
    "capacity": 4,
    "vials": [
      [
        0,
        4,
        4
      ],
      [
        3,
        2
      ],
      [
        2,
        2,
        5,
        1
      ],
      [
        3,
        0,
        3,
        2
      ],
      [
        1
      ],
      [
        5,
        0,
        4
      ],
      [
        0,
        5,
        5
      ],
      [
        1,
        1,
        4,
        3
      ]
    ],
    "minMoves": 15,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 30,
    "chapter": 2,
    "colors": 5,
    "capacity": 4,
    "vials": [
      [
        1,
        3,
        0
      ],
      [
        1,
        3
      ],
      [
        2,
        0
      ],
      [
        3
      ],
      [
        3,
        1,
        2,
        4
      ],
      [
        2,
        4,
        4,
        4
      ],
      [
        0,
        0,
        1,
        2
      ]
    ],
    "minMoves": 13,
    "unlimitedUndo": false,
    "breather": true
  },
  {
    "level": 31,
    "chapter": 3,
    "colors": 6,
    "capacity": 4,
    "vials": [
      [
        0,
        0,
        3,
        1
      ],
      [
        0,
        3
      ],
      [
        2,
        2,
        2,
        1
      ],
      [
        1,
        3,
        1
      ],
      [
        4,
        4,
        4,
        5
      ],
      [
        5
      ],
      [
        5,
        3,
        4
      ],
      [
        2,
        0,
        5
      ]
    ],
    "minMoves": 15,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 32,
    "chapter": 3,
    "colors": 6,
    "capacity": 4,
    "vials": [
      [
        0
      ],
      [
        1,
        3,
        3,
        2
      ],
      [
        5,
        4,
        5,
        4
      ],
      [
        0,
        2,
        3,
        0
      ],
      [
        3,
        5,
        4,
        0
      ],
      [
        5,
        4
      ],
      [
        2,
        2
      ],
      [
        1,
        1,
        1
      ]
    ],
    "minMoves": 15,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 33,
    "chapter": 3,
    "colors": 6,
    "capacity": 4,
    "vials": [
      [
        0,
        2,
        2,
        4
      ],
      [
        1
      ],
      [
        2,
        0,
        4,
        3
      ],
      [
        1,
        1,
        3
      ],
      [
        4
      ],
      [
        5,
        4,
        5,
        3
      ],
      [
        5,
        0,
        0
      ],
      [
        1,
        3,
        5,
        2
      ]
    ],
    "minMoves": 16,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 34,
    "chapter": 3,
    "colors": 6,
    "capacity": 4,
    "vials": [
      [
        4,
        3,
        4
      ],
      [
        1,
        1,
        3
      ],
      [
        0,
        1,
        0,
        4
      ],
      [
        2,
        5,
        2,
        4
      ],
      [
        1,
        5,
        5
      ],
      [],
      [
        3,
        5,
        3,
        2
      ],
      [
        0,
        2,
        0
      ]
    ],
    "minMoves": 18,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 35,
    "chapter": 3,
    "colors": 5,
    "capacity": 4,
    "vials": [
      [
        2,
        1,
        1,
        1
      ],
      [
        4,
        1
      ],
      [
        4,
        3,
        0,
        3
      ],
      [],
      [
        2,
        0
      ],
      [
        2,
        2,
        4,
        0
      ],
      [
        3,
        3,
        0,
        4
      ]
    ],
    "minMoves": 13,
    "unlimitedUndo": false,
    "breather": true
  },
  {
    "level": 36,
    "chapter": 3,
    "colors": 7,
    "capacity": 4,
    "vials": [
      [
        3,
        2,
        0
      ],
      [
        1,
        1,
        3,
        4
      ],
      [
        2,
        3,
        3,
        5
      ],
      [
        2
      ],
      [
        4,
        6
      ],
      [
        5,
        2,
        4
      ],
      [
        0,
        1,
        6,
        0
      ],
      [
        1,
        6,
        6,
        4
      ],
      [
        0,
        5,
        5
      ]
    ],
    "minMoves": 18,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 37,
    "chapter": 3,
    "colors": 7,
    "capacity": 4,
    "vials": [
      [
        5,
        3,
        5,
        5
      ],
      [
        1,
        6
      ],
      [
        2,
        2,
        0
      ],
      [
        3,
        1,
        5,
        0
      ],
      [
        4,
        0,
        6
      ],
      [
        4,
        1,
        1,
        6
      ],
      [
        0
      ],
      [
        4,
        4,
        2,
        6
      ],
      [
        3,
        3,
        2
      ]
    ],
    "minMoves": 18,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 38,
    "chapter": 3,
    "colors": 7,
    "capacity": 4,
    "vials": [
      [
        5,
        0,
        6,
        0
      ],
      [
        1
      ],
      [
        0,
        1,
        2
      ],
      [
        3,
        4,
        5
      ],
      [
        4,
        4,
        4,
        5
      ],
      [
        3,
        1,
        6
      ],
      [
        6,
        2,
        3,
        3
      ],
      [
        0,
        6,
        2,
        5
      ],
      [
        1,
        2
      ]
    ],
    "minMoves": 19,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 39,
    "chapter": 3,
    "colors": 7,
    "capacity": 4,
    "vials": [
      [
        6,
        3,
        2
      ],
      [
        1,
        4,
        1,
        0
      ],
      [],
      [
        3,
        3,
        3,
        1
      ],
      [
        4,
        5,
        0,
        4
      ],
      [
        5
      ],
      [
        0,
        0,
        5,
        5
      ],
      [
        6,
        6,
        1,
        6
      ],
      [
        2,
        4,
        2,
        2
      ]
    ],
    "minMoves": 17,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 40,
    "chapter": 3,
    "colors": 6,
    "capacity": 4,
    "vials": [
      [
        0
      ],
      [
        1,
        4,
        1,
        4
      ],
      [
        3,
        2,
        1,
        3
      ],
      [
        3,
        1
      ],
      [
        4,
        4,
        5
      ],
      [
        5,
        5,
        5
      ],
      [
        3,
        2,
        0
      ],
      [
        0,
        2,
        2,
        0
      ]
    ],
    "minMoves": 15,
    "unlimitedUndo": false,
    "breather": true
  },
  {
    "level": 41,
    "chapter": 4,
    "colors": 7,
    "capacity": 4,
    "vials": [
      [
        0,
        0
      ],
      [
        3,
        1,
        3
      ],
      [
        3,
        1,
        5,
        0
      ],
      [],
      [
        4,
        4,
        3,
        1
      ],
      [
        2,
        2,
        6,
        2
      ],
      [
        6,
        5,
        6
      ],
      [
        4,
        4,
        5,
        1
      ],
      [
        5,
        2,
        6,
        0
      ]
    ],
    "minMoves": 18,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 42,
    "chapter": 4,
    "colors": 7,
    "capacity": 4,
    "vials": [
      [
        4,
        3,
        1
      ],
      [
        0,
        5,
        0
      ],
      [
        2,
        2,
        5
      ],
      [
        3,
        6,
        0,
        1
      ],
      [
        4,
        3,
        2,
        5
      ],
      [
        4
      ],
      [
        6,
        6,
        6,
        5
      ],
      [
        4,
        2,
        1,
        0
      ],
      [
        1,
        3
      ]
    ],
    "minMoves": 19,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 43,
    "chapter": 4,
    "colors": 7,
    "capacity": 4,
    "vials": [
      [
        4,
        5,
        1,
        4
      ],
      [
        4
      ],
      [
        2,
        2,
        2,
        1
      ],
      [
        3
      ],
      [
        0,
        6
      ],
      [
        5,
        1,
        3,
        1
      ],
      [
        0,
        4,
        3,
        5
      ],
      [
        6,
        5,
        2,
        6
      ],
      [
        0,
        0,
        6,
        3
      ]
    ],
    "minMoves": 19,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 44,
    "chapter": 4,
    "colors": 7,
    "capacity": 4,
    "vials": [
      [
        6
      ],
      [
        5,
        6,
        1,
        3
      ],
      [
        2,
        2,
        1,
        4
      ],
      [
        3,
        0,
        1,
        0
      ],
      [
        4,
        4,
        4,
        3
      ],
      [
        5,
        5,
        1,
        0
      ],
      [
        6,
        0
      ],
      [
        2,
        2,
        6
      ],
      [
        5,
        3
      ]
    ],
    "minMoves": 18,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 45,
    "chapter": 4,
    "colors": 6,
    "capacity": 4,
    "vials": [
      [
        0,
        4,
        5,
        1
      ],
      [
        1,
        1,
        4
      ],
      [
        0,
        3,
        5,
        3
      ],
      [],
      [
        1,
        2,
        3,
        4
      ],
      [
        3,
        0
      ],
      [
        4,
        2,
        2
      ],
      [
        2,
        0,
        5,
        5
      ]
    ],
    "minMoves": 16,
    "unlimitedUndo": false,
    "breather": true
  },
  {
    "level": 46,
    "chapter": 4,
    "colors": 8,
    "capacity": 4,
    "vials": [
      [
        7,
        4,
        0,
        2
      ],
      [
        0,
        0,
        1,
        5
      ],
      [
        2,
        2
      ],
      [
        3,
        5,
        4,
        4
      ],
      [
        3,
        1,
        5,
        7
      ],
      [
        6,
        6,
        0
      ],
      [
        2
      ],
      [
        7,
        7,
        5
      ],
      [
        6,
        3,
        6
      ],
      [
        1,
        1,
        4,
        3
      ]
    ],
    "minMoves": 20,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 47,
    "chapter": 4,
    "colors": 8,
    "capacity": 4,
    "vials": [
      [
        0,
        2,
        7,
        1
      ],
      [
        2,
        3,
        7,
        4
      ],
      [
        2,
        5,
        0,
        4
      ],
      [
        3,
        2,
        6
      ],
      [
        3,
        0,
        1
      ],
      [
        5,
        5,
        5
      ],
      [
        6,
        6,
        3,
        1
      ],
      [
        7,
        7,
        4,
        4
      ],
      [
        6
      ],
      [
        0,
        1
      ]
    ],
    "minMoves": 21,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 48,
    "chapter": 4,
    "colors": 8,
    "capacity": 4,
    "vials": [
      [
        3,
        7,
        4,
        5
      ],
      [
        1,
        6,
        7,
        0
      ],
      [
        2,
        0,
        2,
        1
      ],
      [
        3,
        6,
        6,
        0
      ],
      [
        4,
        7,
        2,
        7
      ],
      [
        5,
        5,
        4,
        5
      ],
      [],
      [],
      [
        3,
        3,
        4,
        0
      ],
      [
        1,
        1,
        6,
        2
      ]
    ],
    "minMoves": 24,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 49,
    "chapter": 4,
    "colors": 8,
    "capacity": 4,
    "vials": [
      [
        0,
        7,
        3,
        5
      ],
      [
        4,
        1,
        1,
        4
      ],
      [
        1
      ],
      [
        3,
        7,
        5,
        0
      ],
      [
        7,
        1,
        7,
        2
      ],
      [
        4,
        5,
        2,
        2
      ],
      [
        6,
        6,
        0,
        3
      ],
      [
        6,
        6,
        2
      ],
      [
        5
      ],
      [
        3,
        4,
        0
      ]
    ],
    "minMoves": 21,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 50,
    "chapter": 4,
    "colors": 7,
    "capacity": 4,
    "vials": [
      [
        0,
        6
      ],
      [
        2,
        2,
        5,
        1
      ],
      [],
      [
        2,
        4,
        5,
        0
      ],
      [
        4,
        6,
        5
      ],
      [
        5,
        4,
        3,
        4
      ],
      [
        6,
        0,
        2,
        1
      ],
      [
        6,
        3,
        3,
        0
      ],
      [
        1,
        1,
        3
      ]
    ],
    "minMoves": 19,
    "unlimitedUndo": false,
    "breather": true
  },
  {
    "level": 51,
    "chapter": 5,
    "colors": 8,
    "capacity": 4,
    "vials": [
      [
        0,
        5,
        0,
        5
      ],
      [
        7
      ],
      [
        2,
        2,
        1,
        5
      ],
      [
        2,
        2,
        3
      ],
      [
        0,
        0,
        3,
        7
      ],
      [
        5,
        7
      ],
      [
        6,
        4,
        4,
        7
      ],
      [
        6,
        1,
        4,
        6
      ],
      [
        6,
        3,
        1
      ],
      [
        3,
        4,
        1
      ]
    ],
    "minMoves": 22,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 52,
    "chapter": 5,
    "colors": 8,
    "capacity": 4,
    "vials": [
      [
        0,
        0,
        3,
        2
      ],
      [
        4,
        0,
        6,
        1
      ],
      [
        6,
        3,
        1
      ],
      [
        3,
        5
      ],
      [
        4,
        4,
        1
      ],
      [
        5,
        3,
        1,
        5
      ],
      [
        2,
        7,
        7
      ],
      [
        7,
        2,
        2
      ],
      [
        6,
        0
      ],
      [
        6,
        5,
        7,
        4
      ]
    ],
    "minMoves": 22,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 53,
    "chapter": 5,
    "colors": 8,
    "capacity": 4,
    "vials": [
      [
        3
      ],
      [
        1,
        0,
        0,
        1
      ],
      [
        2,
        5
      ],
      [
        3,
        7,
        2
      ],
      [
        4,
        4,
        0,
        5
      ],
      [
        1,
        5,
        2,
        7
      ],
      [
        6,
        1,
        4,
        4
      ],
      [
        7,
        5
      ],
      [
        6,
        6,
        3,
        2
      ],
      [
        3,
        0,
        7,
        6
      ]
    ],
    "minMoves": 22,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 54,
    "chapter": 5,
    "colors": 8,
    "capacity": 4,
    "vials": [
      [
        1,
        1,
        7,
        4
      ],
      [
        2,
        4,
        4,
        7
      ],
      [
        5,
        3
      ],
      [
        2,
        3,
        6
      ],
      [
        4,
        0
      ],
      [
        5,
        2,
        2,
        7
      ],
      [
        6,
        5,
        0,
        1
      ],
      [
        7,
        1,
        3,
        6
      ],
      [
        6
      ],
      [
        0,
        0,
        5,
        3
      ]
    ],
    "minMoves": 22,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 55,
    "chapter": 5,
    "colors": 7,
    "capacity": 4,
    "vials": [
      [
        5,
        5,
        3,
        2
      ],
      [
        1
      ],
      [
        1,
        0,
        1,
        0
      ],
      [
        3,
        6,
        1
      ],
      [
        4,
        4,
        0,
        4
      ],
      [
        2,
        4
      ],
      [
        6,
        5,
        6
      ],
      [
        5,
        0,
        3
      ],
      [
        2,
        2,
        3,
        6
      ]
    ],
    "minMoves": 19,
    "unlimitedUndo": false,
    "breather": true
  },
  {
    "level": 56,
    "chapter": 5,
    "colors": 9,
    "capacity": 4,
    "vials": [
      [
        0,
        3,
        6,
        2
      ],
      [
        1,
        8,
        8,
        8
      ],
      [
        0,
        6,
        2,
        2
      ],
      [
        3,
        1,
        5,
        4
      ],
      [
        3,
        2,
        4,
        5
      ],
      [
        7,
        8
      ],
      [
        1,
        6,
        5,
        6
      ],
      [
        7,
        7,
        7,
        3
      ],
      [],
      [
        0,
        1,
        0,
        5
      ],
      [
        4,
        4
      ]
    ],
    "minMoves": 25,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 57,
    "chapter": 5,
    "colors": 9,
    "capacity": 4,
    "vials": [
      [
        0,
        4,
        4,
        8
      ],
      [
        5,
        7
      ],
      [
        2,
        2,
        8,
        3
      ],
      [
        1,
        2,
        5,
        7
      ],
      [
        4
      ],
      [
        5,
        5,
        6,
        3
      ],
      [
        6,
        6,
        1,
        3
      ],
      [
        7,
        1,
        6,
        4
      ],
      [
        0,
        8,
        3
      ],
      [
        0,
        1,
        2
      ],
      [
        0,
        8,
        7
      ]
    ],
    "minMoves": 25,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 58,
    "chapter": 5,
    "colors": 9,
    "capacity": 4,
    "vials": [
      [
        0,
        0,
        7,
        0
      ],
      [
        1
      ],
      [
        2,
        2,
        7,
        1
      ],
      [
        3,
        1,
        4
      ],
      [
        4,
        0,
        4
      ],
      [
        5,
        5,
        3,
        7
      ],
      [
        6,
        5,
        4
      ],
      [
        7,
        6,
        6,
        1
      ],
      [
        8,
        3
      ],
      [
        8,
        2,
        3,
        2
      ],
      [
        8,
        5,
        6,
        8
      ]
    ],
    "minMoves": 23,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 59,
    "chapter": 5,
    "colors": 9,
    "capacity": 4,
    "vials": [
      [
        0,
        3,
        4,
        7
      ],
      [
        5,
        5,
        6,
        5
      ],
      [
        2,
        8,
        6
      ],
      [
        3,
        3,
        8
      ],
      [
        4,
        5,
        2,
        6
      ],
      [
        1,
        8,
        0
      ],
      [
        6,
        1,
        1,
        4
      ],
      [
        7,
        7,
        2,
        4
      ],
      [
        3,
        2,
        7
      ],
      [
        8,
        0,
        0
      ],
      [
        1
      ]
    ],
    "minMoves": 22,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 60,
    "chapter": 5,
    "colors": 8,
    "capacity": 4,
    "vials": [
      [
        3
      ],
      [
        1,
        4,
        7,
        0
      ],
      [
        2,
        0
      ],
      [
        3,
        2,
        5,
        6
      ],
      [
        4
      ],
      [
        7,
        2,
        0,
        0
      ],
      [
        4,
        1,
        6,
        2
      ],
      [
        7,
        3,
        6,
        3
      ],
      [
        7,
        1,
        1,
        6
      ],
      [
        5,
        4,
        5,
        5
      ]
    ],
    "minMoves": 24,
    "unlimitedUndo": false,
    "breather": true
  },
  {
    "level": 61,
    "chapter": 5,
    "colors": 9,
    "capacity": 4,
    "vials": [
      [
        0,
        0
      ],
      [
        1,
        6,
        0,
        4
      ],
      [
        7,
        7,
        7,
        3
      ],
      [
        3,
        1,
        8
      ],
      [
        5,
        7,
        4,
        2
      ],
      [
        5,
        1,
        4
      ],
      [
        6,
        4,
        6,
        5
      ],
      [
        3,
        2,
        6,
        1
      ],
      [
        8,
        3,
        0,
        5
      ],
      [
        2
      ],
      [
        8,
        8,
        2
      ]
    ],
    "minMoves": 24,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 62,
    "chapter": 5,
    "colors": 9,
    "capacity": 4,
    "vials": [
      [
        2,
        6,
        7,
        6
      ],
      [
        1,
        6
      ],
      [
        0,
        7
      ],
      [
        3,
        3,
        2,
        1
      ],
      [
        4,
        4,
        3
      ],
      [
        5,
        7,
        4,
        2
      ],
      [
        5,
        6,
        0,
        0
      ],
      [
        8,
        8,
        8
      ],
      [
        3,
        1
      ],
      [
        2,
        1,
        5,
        8
      ],
      [
        5,
        7,
        0,
        4
      ]
    ],
    "minMoves": 24,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 63,
    "chapter": 5,
    "colors": 9,
    "capacity": 4,
    "vials": [
      [
        8,
        8,
        2
      ],
      [
        1,
        6,
        3,
        2
      ],
      [],
      [
        0,
        7,
        2
      ],
      [
        4,
        0,
        0,
        1
      ],
      [
        1,
        1,
        3,
        7
      ],
      [
        6,
        7,
        5
      ],
      [
        0,
        8,
        2,
        3
      ],
      [
        4,
        5,
        4,
        3
      ],
      [
        5,
        6,
        6,
        4
      ],
      [
        5,
        7,
        8
      ]
    ],
    "minMoves": 26,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 64,
    "chapter": 5,
    "colors": 9,
    "capacity": 4,
    "vials": [
      [
        7,
        4,
        0,
        8
      ],
      [
        7,
        0,
        4,
        1
      ],
      [
        6,
        0,
        3
      ],
      [
        5,
        3,
        3,
        2
      ],
      [
        4,
        2,
        7
      ],
      [
        5,
        5,
        5
      ],
      [
        6,
        2,
        8
      ],
      [
        7,
        0,
        3
      ],
      [
        1,
        1,
        1,
        4
      ],
      [
        8,
        2,
        8
      ],
      [
        6,
        6
      ]
    ],
    "minMoves": 25,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 65,
    "chapter": 5,
    "colors": 8,
    "capacity": 4,
    "vials": [
      [
        0,
        0,
        1,
        6
      ],
      [
        7,
        3,
        3
      ],
      [
        2,
        1,
        7
      ],
      [
        3,
        6,
        4
      ],
      [
        4,
        1,
        5,
        5
      ],
      [
        5,
        2
      ],
      [
        5,
        6,
        7
      ],
      [
        2,
        3,
        4
      ],
      [
        7,
        0,
        2
      ],
      [
        6,
        4,
        0,
        1
      ]
    ],
    "minMoves": 22,
    "unlimitedUndo": false,
    "breather": true
  },
  {
    "level": 66,
    "chapter": 5,
    "colors": 10,
    "capacity": 4,
    "vials": [
      [
        4,
        4,
        2
      ],
      [
        7,
        2,
        1,
        2
      ],
      [
        8
      ],
      [
        8,
        3,
        0
      ],
      [
        4,
        4,
        7,
        1
      ],
      [
        5,
        5,
        5,
        7
      ],
      [
        6,
        0,
        6,
        6
      ],
      [
        9,
        1,
        0,
        6
      ],
      [
        8,
        8
      ],
      [
        9,
        3,
        0,
        3
      ],
      [
        1,
        3,
        2,
        9
      ],
      [
        9,
        7,
        5
      ]
    ],
    "minMoves": 28,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 67,
    "chapter": 5,
    "colors": 10,
    "capacity": 4,
    "vials": [
      [
        8
      ],
      [
        1,
        9,
        6,
        7
      ],
      [
        2,
        5,
        0,
        6
      ],
      [
        3,
        3,
        3,
        4
      ],
      [
        4,
        3,
        1,
        0
      ],
      [
        5,
        5,
        6,
        7
      ],
      [
        1,
        2,
        8,
        2
      ],
      [
        1,
        9,
        2,
        0
      ],
      [],
      [
        9,
        9,
        5,
        0
      ],
      [
        7,
        7,
        8
      ],
      [
        4,
        4,
        8,
        6
      ]
    ],
    "minMoves": 26,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 68,
    "chapter": 5,
    "colors": 10,
    "capacity": 4,
    "vials": [
      [
        0,
        0,
        6,
        9
      ],
      [
        2,
        8,
        4,
        6
      ],
      [
        2,
        2,
        3,
        1
      ],
      [
        9,
        7,
        7
      ],
      [
        4,
        1,
        1,
        4
      ],
      [
        0,
        8
      ],
      [
        3,
        5,
        4,
        8
      ],
      [
        7,
        1
      ],
      [
        6,
        7,
        5,
        0
      ],
      [
        9,
        6,
        8,
        9
      ],
      [
        3,
        3,
        2
      ],
      [
        5,
        5
      ]
    ],
    "minMoves": 26,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 69,
    "chapter": 5,
    "colors": 10,
    "capacity": 4,
    "vials": [
      [
        0,
        0,
        4,
        1
      ],
      [
        3,
        2,
        9
      ],
      [
        2,
        2,
        4
      ],
      [
        3,
        8,
        8,
        6
      ],
      [
        4,
        1
      ],
      [
        5,
        4,
        0,
        6
      ],
      [
        6,
        2,
        5
      ],
      [
        7,
        7,
        3,
        6
      ],
      [
        8,
        1
      ],
      [
        9,
        5,
        1,
        3
      ],
      [
        5,
        8,
        0
      ],
      [
        9,
        9,
        7,
        7
      ]
    ],
    "minMoves": 26,
    "unlimitedUndo": false,
    "breather": false
  },
  {
    "level": 70,
    "chapter": 5,
    "colors": 9,
    "capacity": 4,
    "vials": [
      [
        7,
        1,
        5,
        6
      ],
      [
        1,
        2,
        3,
        5
      ],
      [
        2,
        2,
        6,
        4
      ],
      [
        3,
        0,
        7,
        3
      ],
      [
        4,
        4,
        8,
        4
      ],
      [
        5,
        5,
        2,
        0
      ],
      [
        6
      ],
      [
        7,
        7,
        6,
        3
      ],
      [
        8,
        1,
        1
      ],
      [
        0
      ],
      [
        8,
        8,
        0
      ]
    ],
    "minMoves": 24,
    "unlimitedUndo": false,
    "breather": true
  }
];
  if (typeof module === "object" && module.exports) module.exports = LEVELS;
  else root.POTION_POUR_LEVELS = LEVELS;
})(typeof self !== "undefined" ? self : this);
