// Generated by tools/sw-build.mjs: do not edit by hand. After changing any shipped file, run
//   node tools/sw-build.mjs petal-patch
// Precaches the game's own files and serves cache-first; CACHE_VERSION is a hash of those files.
var CACHE_VERSION = 'petal-patch-f343066f';
var FILES = [
  './',
  'art/art.js',
  'art/bloom.svg',
  'art/flower.svg',
  'art/ladybug.svg',
  'art/tex-brick.svg',
  'art/tex-dots.svg',
  'art/tex-furrows.svg',
  'art/tex-gravel.svg',
  'art/tex-rings.svg',
  'art/tex-rows.svg',
  'art/tex-sprouts.svg',
  'art/tex-stripes.svg',
  'demo.js',
  'game.js',
  'icon-192.png',
  'icon-512.png',
  'icon-maskable-512.png',
  'index.html',
  'input.js',
  'levels.js',
  'manifest.webmanifest',
  'model.mjs',
  'register-sw.js',
  'render.js',
  'rules.mjs',
  'run.mjs',
  'save.mjs',
  'share.js',
  'skin.css',
  'solver.mjs',
  'theme.js',
  'tokens.css',
  'ui-kit.css',
  'ui-kit.js'
];

self.addEventListener('install', function (e) {
  e.waitUntil(caches.open(CACHE_VERSION).then(function (c) { return c.addAll(FILES); }).then(function () { return self.skipWaiting(); }));
});

self.addEventListener('activate', function (e) {
  e.waitUntil(caches.keys().then(function (keys) {
    return Promise.all(keys.filter(function (k) { return k.indexOf('petal-patch-') === 0 && k !== CACHE_VERSION; })
      .map(function (k) { return caches.delete(k); }));
  }).then(function () { return self.clients.claim(); }));
});

self.addEventListener('fetch', function (e) {
  if (e.request.method !== 'GET') return;
  e.respondWith(caches.match(e.request, { ignoreSearch: true }).then(function (hit) { return hit || fetch(e.request); }));
});
