// Generated by tools/sw-build.mjs: do not edit by hand. After changing any shipped file, run
//   node tools/sw-build.mjs cannonball-family
// Precaches the game's own files and serves cache-first; CACHE_VERSION is a hash of those files.
var CACHE_VERSION = 'cannonball-family-fa8d24c4';
var FILES = [
  './',
  'aim.js',
  'audio.js',
  'daily-table.js',
  'daily.js',
  'family-sheet.js',
  'family.js',
  'favicon-32.png',
  'fonts/AlfaSlabOne-OFL.txt',
  'fonts/AlfaSlabOne.woff2',
  'fonts/AtkinsonHyperlegible-400.woff2',
  'fonts/AtkinsonHyperlegible-700.woff2',
  'fonts/AtkinsonHyperlegible-OFL.txt',
  'game.js',
  'generator.js',
  'icon-192.png',
  'icon-512.png',
  'icon-maskable-512.png',
  'index.html',
  'input.js',
  'knacks.js',
  'level-table.js',
  'levels.js',
  'manifest.json',
  'physics.js',
  'progress.js',
  'register-sw.js',
  'render.js',
  'rng.js',
  'save.js',
  'sim.js',
  'skin.css',
  'style.css',
  'theme.js',
  'tokens.css',
  'troupe.js',
  'ui-kit.css',
  'ui-kit.js'
];

self.addEventListener('install', function (e) {
  e.waitUntil(caches.open(CACHE_VERSION).then(function (c) { return c.addAll(FILES); }).then(function () { return self.skipWaiting(); }));
});

self.addEventListener('activate', function (e) {
  e.waitUntil(caches.keys().then(function (keys) {
    return Promise.all(keys.filter(function (k) { return k.indexOf('cannonball-family-') === 0 && k !== CACHE_VERSION; })
      .map(function (k) { return caches.delete(k); }));
  }).then(function () { return self.clients.claim(); }));
});

self.addEventListener('fetch', function (e) {
  if (e.request.method !== 'GET') return;
  e.respondWith(caches.match(e.request, { ignoreSearch: true }).then(function (hit) { return hit || fetch(e.request); }));
});
