// Cannonball Family re-skin config (Game Standard v2 §2.5). A classic script, loaded before game.js. Editing this
// file must be enough to re-skin names, text, colours and image slots. Image paths are relative to the game
// folder; every image slot has a drawn default (null). Photos never go in this file (they stay on the device).
window.THEME = {
  title: "Cannonball Family",
  familyName: "Bells", // the family's default name ("The Flying Bells"); a name the player saves always wins
  text: {
    play: "Play",
    levels: "Levels",
    back: "Back",
    level: "Level",
    stars: "Stars",
    cleared: "Cleared",
    family: "Our family",
    familyTitle: "Our family",
    familyName: "Family name",
    addMember: "+ Add member",
    sixOfSix: "6 of 6",
    clearPhotos: "Clear photos",
    save: "Save",
    close: "Close",
    name: "Name",
    colour: "Colour",
    look: "Look",
    photo: "Photo",
    remove: "Remove",
    photoTooBig: "That photo is too big. Try another.",
    photoFailed: "That photo could not be read.",
    photosCleared: "Photos cleared.",
    retry: "Retry",
    theFlying: "The Flying",
    next: "Next",
    win: "The Flying {family}!", // {family} is cast.family (DESIGN.md §8's own card example: "The Flying Bells!")
    lose: "The tins win this time",
    didntFly: "{names} didn't need to fly", // {names} e.g. "Gramps and Kid" (DESIGN.md §8's own card example)
    shots: "Shots",
    fuse: "Fuse",
    best: "Best",
    dailyTower: "Daily tower",
    dailyLabel: "Family Tower",
    practice: "Practice",
    share: "Share",
    shareCopied: "Copied! Paste it anywhere.",
    demoGoal: "Knock down every tin",
    demoRule: "One shot each. If the family runs out, the tins win",
    demoSkip: "Tap to skip",
    paused: "Paused",
    resume: "Resume",
    restart: "Restart",
    howToPlay: "How to play",
    sound: "Sound",
    reducedMotion: "Reduced motion",
    howTo1: "Pull back from anywhere, then let go.",
    howTo2: "Knock down every tin. One shot per member.",
    howTo3: "Stars are the members who didn't need to fly.",
    about: "About",
    privacyLine: "Your family's names and photos are saved only on this device. They are never uploaded, and they never appear in a share line.",
    madeBy: "Made by The Game Company",
    fontCredit: "Fonts: Alfa Slab One, Atkinson Hyperlegible (SIL OFL)",
    chapter1: "Chapter 1",
    chapter2: "Chapter 2",
    chapter3: "Chapter 3",
    of6: "of 6",
    more: "Colour and look",
  },
  colors: {},
  images: {
    cover: null,
  },
};
